#!/usr/bin/env bash
# Copyright (C) ConfigHub, Inc.
# SPDX-License-Identifier: MIT
#
# Generate THIRD_PARTY_LICENSES.txt for the registrybot binary shipped in the image.
#
# The file lists every third-party Go module linked into the binary together with
# the full text of each module's license, generated from the compiled import graph
# via google/go-licenses so it reflects exactly what is distributed. The same run
# fails if a forbidden or restricted (copyleft) license is linked in.
#
# Run from the repo root and commit the result:
#   ./scripts/gen-third-party-licenses.sh
# CI regenerates it on every dependency change and fails if the committed copy
# is stale (.github/workflows/third-party-licenses.yml).
#
# Needs a native Go toolchain at least as new as go.mod requires. A toolchain
# served from the module cache makes go-licenses fail with "does not have module
# info" for stdlib packages (go-licenses issue #128); on such a host run it in
# the golang:1.25 image instead:
#   docker run --rm -v "$PWD":/src -w /src -e GOTOOLCHAIN=local golang:1.25 \
#     sh -c 'git config --global --add safe.directory /src && ./scripts/gen-third-party-licenses.sh'

set -euo pipefail

# Pinned for reproducible output. Bump deliberately.
GOLICENSES_VERSION="v2.0.1"

# First-party module prefixes: ConfigHub's own code, not third-party.
IGNORE=(
  "github.com/confighub/registrybot"
  "github.com/confighub/sdk"
)

# License classes that must never be linked into a distributed binary.
# forbidden: e.g. AGPL. restricted: e.g. GPL/LGPL/CDDL, whose source-disclosure
# obligations would attach to the binary.
DISALLOWED_TYPES="forbidden,restricted"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="${REPO_ROOT}/THIRD_PARTY_LICENSES.txt"

ignore_args=()
for prefix in "${IGNORE[@]}"; do
  ignore_args+=("--ignore" "${prefix}")
done

golicenses() {
  # Run the pinned tool without adding it to go.mod.
  ( cd "${REPO_ROOT}" && \
    GOFLAGS=-mod=mod go run "github.com/google/go-licenses/v2@${GOLICENSES_VERSION}" "$@" )
}

tmp="$(mktemp -d)"
trap 'rm -rf "${tmp}"' EXIT

echo "==> Checking for disallowed license types (${DISALLOWED_TYPES})..."
golicenses check . "${ignore_args[@]}" --disallowed_types "${DISALLOWED_TYPES}"

echo "==> Collecting license texts..."
golicenses save . "${ignore_args[@]}" --save_path "${tmp}/texts" --force

echo "==> Building summary..."
# CSV columns: module import path, license URL, license type.
golicenses report . "${ignore_args[@]}" > "${tmp}/summary.csv" 2>/dev/null
# Deterministic ordering so the committed file is stable across runs.
sort -o "${tmp}/summary.csv" "${tmp}/summary.csv"

echo "==> Writing ${OUTPUT}..."
{
  echo "registrybot — Third-Party Software Notices"
  echo "======================================"
  echo
  echo "The registrybot container image includes the third-party open-source Go modules"
  echo "listed below, statically linked into the registrybot binary. Each is distributed"
  echo "under its own license, the full text of which is reproduced further down in"
  echo "this file. Operating-system packages from the base image are covered"
  echo "separately in OS_LICENSE_NOTICE.txt. This file is generated by"
  echo "scripts/gen-third-party-licenses.sh; do not edit it by hand."
  echo
  echo "SUMMARY (module — license type — source)"
  echo "----------------------------------------"
  while IFS=, read -r module url ltype; do
    [ -z "${module}" ] && continue
    printf '  %-55s %-12s %s\n' "${module}" "${ltype}" "${url}"
  done < "${tmp}/summary.csv"
  echo
  echo "================================================================================"
  echo "FULL LICENSE TEXTS"
  echo "================================================================================"

  while IFS=, read -r module url ltype; do
    [ -z "${module}" ] && continue
    echo
    echo "--------------------------------------------------------------------------------"
    echo "Module:  ${module}"
    echo "License: ${ltype}"
    echo "Source:  ${url}"
    echo "--------------------------------------------------------------------------------"
    echo
    # go-licenses preserves the original license filename (LICENSE, COPYING, ...).
    license_file="$(find "${tmp}/texts/${module}" -maxdepth 1 -type f 2>/dev/null | sort | head -1 || true)"
    if [ -n "${license_file}" ] && [ -f "${license_file}" ]; then
      cat "${license_file}"
    else
      echo "[license text not captured — see ${url}]"
    fi
    echo
  done < "${tmp}/summary.csv"
} > "${OUTPUT}"

count="$(grep -c '^Module:' "${OUTPUT}" || true)"
echo "==> Done. ${OUTPUT} covers ${count} modules."
